In [1]:
import numpy as np
# Create an array
civilian_birth = np.array([4352, 233, 3245, 256, 2394])
civilian_birth

np.zeros((3, 6)) # special arrays with numpy

np.linspace(0, 1, 5) # 0 to 1 (inclusive) with 5 points

a = np.array([0, 1])
b = np.array([2, 3])
ab = np.stack((a, b)).T # stacking arrays
print(ab)


[[0 2]
 [1 3]]


In [7]:
floatVar = 3.145
intVar = floatVar.asty

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [2]:
A = np.array([[4,5],[6,-3]]) 
b = np.array([23, 3]) 
x,y = np.linalg.solve(A,b) 
print("value of x = ",x,"\n value of y = ",y)

matrix = np.matrix([[1, 5, 3], [9, 5, 6], [2, 8, 9]])
matrix.flatten() # Flatten matrix

np.linalg.det(matrix)  # Return determinant of matrix

matrix.diagonal().sum()  # Calculate the trace of the matrix

np.linalg.inv(matrix) # Calculate inverse of matrix

value of x =  2.0 
 value of y =  3.0


matrix([[ 0.01851852,  0.12962963, -0.09259259],
        [ 0.42592593, -0.01851852, -0.12962963],
        [-0.38271605, -0.01234568,  0.24691358]])

In [17]:
A = np.array([[4,5],[6,-3]]) 
A
np.linalg.inv(A)

array([[ 0.07142857,  0.11904762],
       [ 0.14285714, -0.0952381 ]])

In [14]:
matrix = np.matrix([[1, 5, 3], [9, 5, 6], [2, 8, 9]])
matrix

matrix([[1, 5, 3],
        [9, 5, 6],
        [2, 8, 9]])

In [15]:

matrix.diagonal().sum()  # Calculate the trace of the matrix

15

In [11]:
matrix.flatten() # Flatten matrix

matrix([[1, 5, 3, 9, 5, 6, 2, 8, 9]])

# Pandas

In [3]:
import pandas as pd
data = ['a','b','c','d']
s = pd.Series(data) # creating a pandas series
print(s)

data = {'name': ['Jason', 'Molly', 'Tina', 'Jake'], 
        'year': [2012, 2012, 2013, 2014], 'reports': [4, 24, 31, 2]}
index = ['Cochice', 'Pima', 'Santa Cruz', 'Maricopa']
df = pd.DataFrame(data, index = index) # Create an dataframe
df

0    a
1    b
2    c
3    d
dtype: object


name  year  reports
Cochice     Jason  2012        4
Pima        Molly  2012       24
Santa Cruz   Tina  2013       31
Maricopa     Jake  2014        2

In [36]:
# Load a csv
url = 'https://raw.githubusercontent.com/anshupandey/WileyNXT/main/DataEngineering/datawh.csv'
df = pd.read_csv(url)
df.head(2)

# Load a JSON file
url = 'https://raw.githubusercontent.com/anshupandey/WileyNXT/main/DataEngineering/server-metrics.json'
df = pd.read_json(url)
df.head(2)

# Save dataframe as csv in the working director
df.to_csv('server_data.csv')


In [38]:
traindata = df [["dates", "Server"]]
traindata

dates     Server
0   1525046400000  Server_02
1   1525132800000  Server_02
2   1525219200000   Server_0
3   1525305600000  Server_01
4   1525392000000   Server_0
5   1525478400000  Server_01
6   1525564800000  Server_01
7   1525651200000  Server_01
8   1525737600000  Server_02
9   1525824000000  Server_01
10  1525910400000   Server_0
11  1525996800000   Server_0
12  1526083200000  Server_01
13  1526169600000  Server_02
14  1526256000000  Server_02
15  1526342400000   Server_0
16  1526428800000  Server_01
17  1526515200000  Server_02
18  1526601600000  Server_02
19  1526688000000  Server_02

In [27]:
df[1:2]

id          dates  Accepted  Rejected    App     Server
1   1  1525132800000      2592       182  App_3  Server_02

In [28]:
import pandas as pd
data = {'name': ['Jason', 'Molly', 'Tina'], 
        'year': [2012, 2012, 2013], 
        'reports': [4, 5, 9],
        'coverage': [25, 62, 70]}
df = pd.DataFrame(data)
df['name'] # View Column

df[['name', 'reports']] # View Two Columns

df[:2] # View First Two Rows

df[df['coverage'] > 50] # Rows Where Coverage>50

# View Rows Where Coverage > 20 & Reports < 6
df[(df['coverage']  > 20) & (df['reports'] < 6)]


name  year  reports  coverage
0  Jason  2012        4        25
1  Molly  2012        5        62

In [33]:

df[(df['coverage']  > 20) & (df['reports'] < 6)]

name  year  reports  coverage
0  Jason  2012        4        25
1  Molly  2012        5        62